apiVersion: v1
kind: Service
metadata:
  name: telemetry-microservice-service
spec:
  type: ClusterIP
  selector:
    app: telemetry-microservice
  ports:
    - port: 6002         # Puerto externo por el que se accederá al servicio
      targetPort: 6002   # Puerto interno del contenedor al que redirige
