apiVersion: v1
kind: Service
metadata:
  name: telemetry-microservice-service
spec:
  type: NodePort
  selector:
    app: telemetry-microservice
  ports:
    - port: 6002         # Puerto del servicio dentro del clúster
      targetPort: 6002   # Puerto del contenedor
      nodePort: 30002    # Puerto accesible desde tu máquina local (rango permitido: 30000–32767)
