apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-service
spec:
  type: ClusterIP
  selector:
    app: webapp-backend
  ports:
    - port: 5001         # Puerto externo por el que se accederá al servicio
      targetPort: 5001   # Puerto interno del contenedor al que redirige
