# Define un grupo de servidores llamado 'backend' que apunta al servicio interno del backend en Kubernetes
upstream backend {
    server webapp-backend-service:5001;  # Nombre DNS interno del servicio del backend (resuelto por Kubernetes)
}

server {
    listen 80;  # El servidor escucha en el puerto HTTP 80 (puerto por defecto para tráfico web sin HTTPS)

    # Configuración para servir archivos estáticos del frontend
    location / {
        root /usr/share/nginx/html;  # Ruta en el contenedor donde están los archivos del frontend (por ejemplo, HTML, CSS, JS)
        index index.html;  # Archivo por defecto si no se especifica uno (por ejemplo, cuando se accede solo a '/')
        
        # Intenta servir directamente el archivo solicitado.
        # Si no existe, redirige a index.html (útil para aplicaciones SPA como las de React o Vue)
        try_files $uri $uri/ /index.html;
    }

    # Configuración para redirigir las peticiones del frontend que comienzan por /tachographs al backend
    location /tachographs {
        proxy_pass http://backend;  # Redirige la solicitud al backend (definido en el bloque upstream)
    }
}