apiVersion: v1 
kind: Secret 
metadata: 
  name: webapp-frontend-secrets
type: Opaque 
data: 
  GOOGLE_MAPS_API_KEY: "QUl6YVN5QWRDLWY2SmdreVNaUFA1NFRuWkttU0d4MHh2bUhKbklZ"
  GOOGLE_MAP_ID: "ZTgyNzc4NGYzNzhiY2I2NGJjNzU1MWE2"