apiVersion: v1
kind: Secret
metadata:
    name: tachograph-secrets
type: Opaque
data: # base64
  TENANT_PASSWORD: "dGVuYW50"
  CUSTOMER_ID: "N2E0NzQ1MDAtMTllZC0xMWYwLTlhNzgtMjFhOTFmZDA2OWI3"
  PRIVATE_KEY_PASSWORD: "UGFzc3dvcmRfRm9yLVByaXZhdGVfS2V5LTEyMzQ1LW4="
  GOOGLE_MAPS_API_KEY: "QUl6YVN5QWRDLWY2SmdreVNaUFA1NFRuWkttU0d4MHh2bUhKbklZ"
