apiVersion: v1
kind: Service
metadata:
  name: events-microservice-service
spec:
  type: ClusterIP
  selector:
    app: events-microservice
  ports:
    - port: 6001         # Puerto externo por el que se accederá al servicio
      targetPort: 6001   # Puerto interno del contenedor al que redirige
